---
- name: Installation proxy nginx
  hosts: prod
  become: true
  tasks:
   - name: Conteneur nginx
     docker_container:
      name: proxy
      image: nginx:alpine
      state: started
      networks:
       - name: network_frontend
      ports:
       - '80:80'
      volumes:
       - ./proxy/default.conf:/etc/nginx/conf.d/default.conf:ro
