---
- name: Installation BD Mysql
  hosts: prod
  become: true
  tasks:
   - name: Creer Volume
     docker_volume:
      name: Sqldata
   - name: Conteneur Mysql
     docker_container:
      name: mysql
      image: mysql:5.7
      restart_policy: always
      networks:
       - name: network_backend1
       - name: network_backend2
      env:
       MYSQL_ROOT_PASSWORD: 'rootpassword'
      ports:
       - '3306:3306'
      volumes:
       - Sqldata:/var/lib/mysql
