---
- name: Installation conteneurs php
  hosts: prod
  become: true
  tasks:
   - name: Image php1
     docker_image:
      name: php1
      source: build
      build: 
       path: ./php1
   - name: Image php2
     docker_image:
      name: php2
      source: build
      build: 
       path: ./php2
   - name: Conteneur php1
     docker_container:
      name: php1
      image: php1
      state: started
      networks:
       - name: network_backend1
      volumes:
       - ./serveur1/html:/usr/local/apache2/htdocs
   - name: Conteneur php2
     docker_container:
      name: php2
      image: php2
      state: started
      networks:
       - name: network_backend2
      volumes:
       - ./serveur2/html:/usr/local/apache2/htdocs
